-- Your SQL goes here
CREATE TABLE items(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    receipt_id INTEGER NOT NULL REFERENCES receipts (id),
    product TEXT NOT NULL,
    price FLOAT NOT NULL,
    discount FLOAT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT 0
)